{
 "title": "K8s Container",
 "description": "Summary metrics about containers running on Kubernetes nodes.",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_created,namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"},pod)"
   },
   {
    "name": "node",
    "query": "label_values(kube_pod_info{pod=~\"$pod\"},node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "description": "Total memory usage of containers across a cluster",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod_name=~\"$pod\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod_name=~\"$pod\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network Traffic (Inbound)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod_name=~\"$pod\", kubernetes_io_hostname=~\"$node\"}[2m])",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network Traffic (Outbound)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod_name=~\"$pod\", kubernetes_io_hostname=~\"$node\"}[2m])",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_io_time_seconds_total{pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_write_seconds_total{pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}